events {
    worker_connections 1024;
}

http {
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" rt=$request_time';

    access_log /var/log/nginx/access.log main;

    upstream content_service {
        server content-service:8080;
    }

    server {
        listen 80;
        server_name _;

        # Reverse Proxy → Spring Boot
        location / {
            proxy_pass         http://content_service;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_read_timeout 60s;
        }

        # Stub-Status für nginx-prometheus-exporter
        location /stub_status {
            stub_status on;
            allow 172.0.0.0/8;   # Docker-Netzwerk
            allow 10.0.0.0/8;
            deny all;
        }
    }
}
